#!/usr/bin/env bash

scriptDir="$( cd "$(dirname "$0")" ; pwd -P )"

cd $scriptDir/../
echo "Installation script running for $(pwd)"

# Client install
cd client
npm install
cd ..

# Server install
cd server
npm install
cp .env.example .env
npm i -g @adonisjs/cli
adonis key:generate
adonis migration:refresh --seed

if [ $(git config gitflow.branch.master) == "" ]; then
    # Override git flow config
    git flow init -f -d

    git config gitflow.branch.master "master"
    git config gitflow.branch.develop "develop"
    git config gitflow.prefix.feature "feature/"
    git config gitflow.prefix.release "release/"
    git config gitflow.prefix.hotfix "hotfix/"
    git config gitflow.prefix.support "support/"
    git config gitflow.prefix.versiontag ""
fi

echo
echo "Setup script executed."
