#!/usr/bin/env bash

# scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
scriptDir="$( cd "$(dirname "$0")" ; pwd -P )"

cd $scriptDir/../
echo "Installation script running for $(pwd)"

if ! [ -a client/package-lock.json ]; then
    cd client
    npm install
    cd ..
fi

if ! [ -a server/package-lock.json ]; then
    cd server
    cp .env.example .env
    npm i -g @adonisjs/cli
    adonis install
fi

if [ $(git config gitflow.branch.master) == "" ]; then
    # Override git flow config
    git flow init -f -d

    git config gitflow.branch.master "master"
    git config gitflow.branch.develop "develop"
    git config gitflow.prefix.feature "feature/"
    git config gitflow.prefix.release "release/"
    git config gitflow.prefix.hotfix "hotfix/"
    git config gitflow.prefix.support "support/"
    git config gitflow.prefix.versiontag "v"
fi

echo
echo "Setup script executed."